/**
 * P0.10 — Script de cleanup des Characters auto-générés orphelins.
 *
 * Contexte : les PNJ auto-créés par `runNarrativePass` sont upsertés AVANT la
 * transaction principale de persistance (Tx B). Si la pass crash après l'upsert
 * (fail fetch provider, timeout Tx B, crash OOM...), le Character reste en DB
 * sans aucune scène ni image liée.
 *
 * Règle de cleanup : on supprime tout Character tel que :
 *   - `autoGenerated = true`
 *   - `createdAt < now - ORPHAN_AGE_HOURS h` (défaut 24)
 *   - aucune entrée dans `Scene.characters` du projet qui cite son `name`
 *   - aucun `SceneImage.panelCast` qui cite son `id`
 *
 * Usage :
 *   pnpm --filter @manga-ai-studio/db exec tsx prisma/cleanup-orphan-autogen-characters.ts
 *   pnpm --filter @manga-ai-studio/db exec tsx prisma/cleanup-orphan-autogen-characters.ts --dry-run
 *   ORPHAN_AGE_HOURS=48 pnpm --filter @manga-ai-studio/db exec tsx prisma/cleanup-orphan-autogen-characters.ts
 *
 * À brancher en cron hebdo (Render / GH Actions / Supabase Edge Scheduler).
 */

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const ORPHAN_AGE_HOURS = Number(process.env.ORPHAN_AGE_HOURS ?? "24");
const DRY_RUN = process.argv.includes("--dry-run");

async function isCharacterReferenced(characterId: string, characterName: string, projectId: string): Promise<boolean> {
  const [sceneHit, panelCastHit, metadataHit] = await Promise.all([
    prisma.chapterScene.findFirst({
      where: {
        chapter: { projectId },
        characters: { has: characterName },
      },
      select: { id: true },
    }),
    prisma.sceneImage.findFirst({
      where: {
        scene: { chapter: { projectId } },
        panelCast: {
          path: ["focus", "characterId"],
          equals: characterId,
        },
      },
      select: { id: true },
    }).catch(() => null),
    prisma.sceneImage.findFirst({
      where: {
        scene: { chapter: { projectId } },
        metadata: {
          path: ["characterIds"],
          array_contains: characterId,
        },
      },
      select: { id: true },
    }).catch(() => null),
  ]);
  return Boolean(sceneHit || panelCastHit || metadataHit);
}

async function main() {
  const cutoff = new Date(Date.now() - ORPHAN_AGE_HOURS * 60 * 60 * 1000);
  console.log(
    `[cleanup-orphan] mode=${DRY_RUN ? "dry-run" : "live"} cutoff=${cutoff.toISOString()} (age > ${ORPHAN_AGE_HOURS}h)`,
  );

  const candidates = await prisma.character.findMany({
    where: {
      autoGenerated: true,
      createdAt: { lt: cutoff },
    },
    select: { id: true, name: true, projectId: true, createdAt: true },
  });

  console.log(`[cleanup-orphan] candidates=${candidates.length}`);

  let toDelete: { id: string; name: string }[] = [];
  for (const c of candidates) {
    const referenced = await isCharacterReferenced(c.id, c.name, c.projectId);
    if (!referenced) {
      toDelete.push({ id: c.id, name: c.name });
    }
  }

  console.log(`[cleanup-orphan] orphans=${toDelete.length}`);
  for (const o of toDelete) {
    console.log(`  - ${o.name} (${o.id})`);
  }

  if (!DRY_RUN && toDelete.length > 0) {
    const result = await prisma.character.deleteMany({
      where: { id: { in: toDelete.map((o) => o.id) } },
    });
    console.log(`[cleanup-orphan] deleted=${result.count}`);
  } else if (DRY_RUN) {
    console.log(`[cleanup-orphan] dry-run: no deletions performed`);
  }
}

main()
  .then(() => prisma.$disconnect())
  .catch(async (err) => {
    console.error("[cleanup-orphan] failed:", err);
    await prisma.$disconnect();
    process.exit(1);
  });
