import type { Prisma, PrismaClient } from "@manga-ai-studio/db";
import type { NpcType, SceneExtra } from "@manga-ai-studio/core";

import { upsertNpcVisualProfile } from "./npc-profile";
import { stableToken } from "./utils";

/** Détermine le type de PNJ selon son importance narrative. */
export function classifyNpcType(extra: SceneExtra): NpcType {
  if (extra.canSpeak) return "narrative";
  if (extra.reusePriority >= 80) return "support";
  return "ambient";
}

function archetypeTemplateKey(extra: SceneExtra): string {
  const m = /(?:legacy|inferred):(.+)$/.exec(extra.archetypeId);
  return m ? m[1] : extra.archetypeId;
}

/**
 * Nom d'affichage candidat pour un `Character` auto-créé lors de la promotion
 * d'un extra. Les extras `ai_generated` / `db_canon` réutilisent le libellé
 * monde plutôt que « Garde 42 ».
 */
export function buildPromotedNpcDisplayName(
  extra: SceneExtra,
  seed: string = extra.id,
): string {
  const key = archetypeTemplateKey(extra);
  const names: Record<string, string> = {
    bartender: "Barman",
    client: "Client",
    guard: "Garde",
    server: "Serveur",
    merchant: "Marchand",
    passerby: "Passant",
    crowd: "Figurant",
    other: "PNJ",
  };

  const labelStem = extra.archetypeLabel.split("(")[0]?.trim() ?? "";
  const useRichLabel =
    (extra.source === "ai_generated" || extra.source === "db_canon")
    && labelStem.length >= 2
    && !/^pnj$/i.test(labelStem);

  const base = useRichLabel
    ? labelStem.slice(0, 80)
    : (names[key] ?? (labelStem || "PNJ"));
  const suffix = parseInt(stableToken(seed).slice(0, 3), 36) % 999 + 1;

  return `${base} ${suffix}`;
}

/**
 * Promeut un extra en personnage narratif (Character DB).
 * Appelé quand un PNJ parle ou devient important narrativement.
 */
export async function promoteExtraToNarrativeNpc(
  prisma: PrismaClient | Prisma.TransactionClient,
  input: {
    projectId: string;
    extraId: string;
    extra: SceneExtra;
    firstDialogue?: string;
  },
): Promise<{ characterId: string; promoted: boolean }> {
  console.log(
    `[scene-extras-registry] Promoting extra ${input.extraId} to narrative NPC`,
  );
  const npcName = buildPromotedNpcDisplayName(input.extra, input.extra.id);
  const npcSlug = `${npcName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")}-${stableToken(input.extra.id)}`;

  const character = await prisma.character.create({
    data: {
      projectId: input.projectId,
      slug: npcSlug,
      name: npcName,
      roleType: "secondary",
      gender:
        input.extra.visualSignature.genderPresentation === "masculine"
          ? "male"
          : input.extra.visualSignature.genderPresentation === "feminine"
            ? "female"
            : null,
      appearance: JSON.stringify(input.extra.visualSignature),
      autoGenerated: true,
      biography: `PNJ auto-généré (${input.extra.archetypeLabel}) apparu dans la scène ${input.extra.sceneId}`,
      traits: [input.extra.archetypeLabel],
      flaws: [],
      secrets: [],
    },
  });

  await upsertNpcVisualProfile(prisma, {
    projectId: input.projectId,
    sceneId: input.extra.sceneId,
    extra: input.extra,
    characterId: character.id,
    forceImportant: true,
  });

  return {
    characterId: character.id,
    promoted: true,
  };
}
