/**
 * Catalogues de `PropTemplate` par domaine narratif.
 *
 * Ces catalogues sont uniquement consommés par le moteur heuristique
 * legacy (`getUniverseProps` + `getAdditionalDomainsOnlyIfExplicitlySignaled`).
 * Le pipeline premium IA-first les ignore quand un `VisualWorldContract`
 * est actif.
 */
import type { PropTemplate } from "./types";

export const COMBAT_NINJA_PROPS: PropTemplate[] = [
  {
    canonicalName: "kunai",
    aliases: ["throwing knife", "ninja knife"],
    category: "weapon",
    narrativeRole: "action_tool",
    defaultVisibilityMode: "in_hand",
    triggers: ["kunai", "ninja", "shinobi", "infiltr", "lancer", "throw"],
    confidence: 0.9,
  },
  {
    canonicalName: "shuriken",
    aliases: ["throwing star", "étoile ninja"],
    category: "weapon",
    narrativeRole: "action_tool",
    defaultVisibilityMode: "in_hand",
    triggers: ["shuriken", "ninja", "shinobi", "étoile", "star"],
    confidence: 0.85,
  },
  {
    canonicalName: "short blade",
    aliases: ["lame courte", "tanto", "ninjato", "wakizashi"],
    category: "weapon",
    narrativeRole: "action_tool",
    defaultVisibilityMode: "in_hand",
    triggers: ["lame", "blade", "sword", "épée", "katana", "tranche", "slashes", "combat"],
    confidence: 0.8,
  },
  {
    canonicalName: "scroll",
    aliases: ["parchemin", "ninja scroll"],
    category: "document",
    narrativeRole: "worldbuilding",
    defaultVisibilityMode: "in_hand",
    triggers: ["parchemin", "scroll", "mission", "ordre", "order"],
    confidence: 0.7,
  },
  {
    canonicalName: "smoke bomb",
    aliases: ["fumigène", "smoke grenade"],
    category: "equipment",
    narrativeRole: "action_tool",
    defaultVisibilityMode: "used_in_action",
    triggers: ["fumée", "smoke", "disparaît", "disappears", "fuite", "escape"],
    confidence: 0.75,
  },
  {
    canonicalName: "holster / pouch",
    aliases: ["étui", "sacoche", "bandeau", "bandolier"],
    category: "equipment",
    narrativeRole: "worldbuilding",
    defaultVisibilityMode: "on_body",
    triggers: ["ninja", "shinobi", "équipement", "equipment", "combat"],
    confidence: 0.65,
  },
];

export const URBAN_TECH_PROPS: PropTemplate[] = [
  {
    canonicalName: "smartphone",
    aliases: ["phone", "téléphone", "mobile", "cellphone"],
    category: "device",
    narrativeRole: "communication",
    defaultVisibilityMode: "in_hand",
    triggers: [
      "appelle",
      "calls",
      "message",
      "texte",
      "text",
      "phone",
      "téléphone",
      "mobile",
    ],
    confidence: 0.9,
  },
  {
    canonicalName: "laptop",
    aliases: ["ordinateur portable", "computer", "notebook"],
    category: "device",
    narrativeRole: "computation",
    defaultVisibilityMode: "on_surface",
    triggers: [
      "ordinateur",
      "laptop",
      "computer",
      "code",
      "coding",
      "programme informatique",
    ],
    confidence: 0.88,
  },
  {
    canonicalName: "screen / monitor",
    aliases: ["écran", "monitor", "display"],
    category: "device",
    narrativeRole: "computation",
    defaultVisibilityMode: "background_support",
    triggers: ["écran", "screen", "monitor", "affiche", "displays"],
    confidence: 0.8,
  },
  {
    canonicalName: "tablet",
    aliases: ["tablette", "iPad", "pad"],
    category: "device",
    narrativeRole: "computation",
    defaultVisibilityMode: "in_hand",
    triggers: ["tablette", "tablet", "pad"],
    confidence: 0.75,
  },
  {
    canonicalName: "earpiece",
    aliases: ["oreillette", "écouteur", "headset", "earphone"],
    category: "device",
    narrativeRole: "communication",
    defaultVisibilityMode: "on_body",
    triggers: ["oreillette", "earpiece", "headset", "communique", "communicates"],
    confidence: 0.8,
  },
  {
    canonicalName: "badge",
    aliases: ["badge", "ID card", "carte d'accès"],
    category: "document",
    narrativeRole: "worldbuilding",
    defaultVisibilityMode: "on_body",
    triggers: [
      "badge",
      "accès",
      "access",
      "identité",
      "identity",
      "sécurité",
      "security",
    ],
    confidence: 0.85,
  },
  {
    canonicalName: "access card",
    aliases: ["carte d'accès", "keycard", "badge magnétique"],
    category: "document",
    narrativeRole: "action_tool",
    defaultVisibilityMode: "in_hand",
    triggers: ["carte d'accès", "keycard", "porte", "door", "déverrouille", "unlocks"],
    confidence: 0.9,
  },
];

export const SURVEILLANCE_HACKING_PROPS: PropTemplate[] = [
  {
    canonicalName: "surveillance monitor",
    aliases: ["moniteur de surveillance", "CCTV screen"],
    category: "device",
    narrativeRole: "evidence",
    defaultVisibilityMode: "background_support",
    triggers: [
      "surveillance",
      "caméra",
      "camera",
      "cctv",
      "moniteur de surveillance",
      "filme secrètement",
    ],
    confidence: 0.85,
  },
  {
    canonicalName: "keyboard",
    aliases: ["clavier", "keyboard"],
    category: "device",
    narrativeRole: "computation",
    defaultVisibilityMode: "on_surface",
    triggers: ["clavier", "keyboard", "hack", "pirate informatique", "pirate"],
    confidence: 0.8,
  },
  {
    canonicalName: "camera",
    aliases: ["caméra", "camera", "webcam"],
    category: "device",
    narrativeRole: "evidence",
    defaultVisibilityMode: "background_support",
    triggers: ["caméra", "camera", "film", "enregistre", "records"],
    confidence: 0.8,
  },
  {
    canonicalName: "document / dossier",
    aliases: ["dossier", "folder", "file", "rapport"],
    category: "document",
    narrativeRole: "evidence",
    defaultVisibilityMode: "in_hand",
    triggers: [
      "dossier",
      "document",
      "fichier",
      "file",
      "rapport",
      "report",
      "preuve",
      "evidence",
    ],
    confidence: 0.85,
  },
  {
    canonicalName: "photo / evidence",
    aliases: ["photo", "photograph", "preuve", "cliché"],
    category: "document",
    narrativeRole: "evidence",
    defaultVisibilityMode: "foreground_insert",
    triggers: ["photo", "photograph", "preuve", "evidence", "cliché", "image"],
    confidence: 0.9,
  },
  {
    canonicalName: "USB drive",
    aliases: ["clé USB", "USB key", "flash drive"],
    category: "device",
    narrativeRole: "action_tool",
    defaultVisibilityMode: "in_hand",
    triggers: [
      "usb",
      "clé usb",
      "flash drive",
      "données",
      "data",
      "transfère",
      "transfers",
    ],
    confidence: 0.85,
  },
  {
    canonicalName: "terminal",
    aliases: ["terminal", "console", "workstation"],
    category: "device",
    narrativeRole: "computation",
    defaultVisibilityMode: "on_surface",
    triggers: [
      "terminal",
      "console",
      "workstation",
      "hack",
      "pirate",
      "système",
      "system",
    ],
    confidence: 0.85,
  },
];

export const MEDICAL_PROPS: PropTemplate[] = [
  {
    canonicalName: "bandage",
    aliases: ["pansement", "bandage", "dressing", "bande"],
    category: "medical",
    narrativeRole: "medical",
    defaultVisibilityMode: "on_body",
    triggers: [
      "blessé",
      "wounded",
      "blessure",
      "wound",
      "soigne",
      "heals",
      "bandage",
      "pansement",
    ],
    confidence: 0.9,
  },
  {
    canonicalName: "medical kit",
    aliases: ["mallette médicale", "trousse de secours", "first aid kit"],
    category: "medical",
    narrativeRole: "medical",
    defaultVisibilityMode: "foreground_insert",
    triggers: ["soins", "medical", "premiers secours", "first aid", "traite", "treats"],
    confidence: 0.8,
  },
  {
    canonicalName: "syringe",
    aliases: ["seringue", "injection", "needle"],
    category: "medical",
    narrativeRole: "medical",
    defaultVisibilityMode: "in_hand",
    triggers: [
      "seringue",
      "syringe",
      "injection",
      "injecte",
      "injects",
      "antidote",
      "poison",
    ],
    confidence: 0.9,
  },
  {
    canonicalName: "stretcher",
    aliases: ["civière", "brancard", "stretcher"],
    category: "medical",
    narrativeRole: "medical",
    defaultVisibilityMode: "background_support",
    triggers: ["civière", "stretcher", "brancard", "transport", "évacue", "evacuates"],
    confidence: 0.75,
  },
];

export const MYSTICAL_PROPS: PropTemplate[] = [
  {
    canonicalName: "talisman",
    aliases: ["talisman", "charm", "amulette"],
    category: "mystical",
    narrativeRole: "ritual",
    defaultVisibilityMode: "in_hand",
    triggers: [
      "talisman",
      "charm",
      "magie",
      "magic",
      "sort",
      "spell",
      "rituel",
      "ritual",
      "parchemin",
      "mystique",
    ],
    confidence: 0.85,
  },
  {
    canonicalName: "grimoire",
    aliases: ["grimoire", "spell book", "livre de sorts"],
    category: "mystical",
    narrativeRole: "ritual",
    defaultVisibilityMode: "in_hand",
    triggers: ["grimoire", "spell book", "livre", "book", "sort", "spell", "incantation"],
    confidence: 0.85,
  },
  {
    canonicalName: "artifact",
    aliases: ["artefact", "artifact", "relique", "relic"],
    category: "mystical",
    narrativeRole: "payoff",
    defaultVisibilityMode: "foreground_insert",
    triggers: [
      "artefact",
      "artifact",
      "relique",
      "relic",
      "objet ancien",
      "ancient object",
    ],
    confidence: 0.9,
  },
  {
    canonicalName: "seal / sigil",
    aliases: ["sceau", "seal", "sigil", "glyphe", "glyph"],
    category: "mystical",
    narrativeRole: "ritual",
    defaultVisibilityMode: "foreground_insert",
    triggers: ["sceau", "seal", "sigil", "glyphe", "glyph", "marque", "mark"],
    confidence: 0.8,
  },
  {
    canonicalName: "amulet",
    aliases: ["amulette", "amulet", "pendentif", "pendant"],
    category: "mystical",
    narrativeRole: "worldbuilding",
    defaultVisibilityMode: "on_body",
    triggers: ["amulette", "amulet", "pendentif", "pendant", "collier", "necklace"],
    confidence: 0.8,
  },
];

export const MILITARY_PROPS: PropTemplate[] = [
  {
    canonicalName: "handgun",
    aliases: ["pistolet", "handgun", "pistol", "revolver"],
    category: "weapon",
    narrativeRole: "threat",
    defaultVisibilityMode: "in_hand",
    triggers: [
      "pistolet",
      "gun",
      "pistol",
      "revolver",
      "tire",
      "shoots",
      "vise",
      "aims",
    ],
    confidence: 0.9,
  },
  {
    canonicalName: "rifle",
    aliases: ["fusil", "rifle", "carabine"],
    category: "weapon",
    narrativeRole: "threat",
    defaultVisibilityMode: "in_hand",
    triggers: ["fusil", "rifle", "carabine", "sniper", "tire", "shoots"],
    confidence: 0.9,
  },
  {
    canonicalName: "holster",
    aliases: ["holster", "étui à arme", "fourreau"],
    category: "equipment",
    narrativeRole: "worldbuilding",
    defaultVisibilityMode: "on_body",
    triggers: [
      "holster",
      "étui",
      "fourreau",
      "militaire",
      "military",
      "soldat",
      "soldier",
    ],
    confidence: 0.7,
  },
];

export const OFFICE_SCHOOL_LAB_PROPS: PropTemplate[] = [
  {
    canonicalName: "notebook",
    aliases: ["cahier", "notebook", "carnet"],
    category: "stationery",
    narrativeRole: "worldbuilding",
    defaultVisibilityMode: "in_hand",
    triggers: [
      "cahier",
      "notebook",
      "carnet",
      "note",
      "écrit",
      "writes",
      "classe",
      "class",
    ],
    confidence: 0.75,
  },
  {
    canonicalName: "pen",
    aliases: ["stylo", "pen", "crayon", "pencil"],
    category: "stationery",
    narrativeRole: "worldbuilding",
    defaultVisibilityMode: "in_hand",
    triggers: ["stylo", "pen", "crayon", "pencil", "écrit", "writes", "signe", "signs"],
    confidence: 0.7,
  },
  {
    canonicalName: "can / drink",
    aliases: ["canette", "can", "boisson", "drink", "verre", "glass"],
    category: "prop",
    narrativeRole: "worldbuilding",
    defaultVisibilityMode: "on_surface",
    triggers: [
      "canette",
      "can",
      "boisson",
      "drink",
      "verre",
      "glass",
      "pause",
      "break",
    ],
    confidence: 0.65,
  },
  {
    canonicalName: "school bag",
    aliases: ["sac", "bag", "sac à dos", "backpack"],
    category: "prop",
    narrativeRole: "worldbuilding",
    defaultVisibilityMode: "on_body",
    triggers: ["sac", "bag", "backpack", "école", "school", "lycée", "student"],
    confidence: 0.7,
  },
  {
    canonicalName: "lab equipment",
    aliases: ["équipement de labo", "lab equipment", "beaker", "éprouvette"],
    category: "prop",
    narrativeRole: "worldbuilding",
    defaultVisibilityMode: "background_support",
    triggers: [
      "labo",
      "lab",
      "laboratoire",
      "laboratory",
      "expérience",
      "experiment",
    ],
    confidence: 0.75,
  },
];
