import type { OntologyEntry, ProceduralEntity, SceneBlueprintInput } from "./types";
import { createSeededRng } from "./seeded-rng";

export const CREATURE_ONTOLOGY: OntologyEntry[] = [
  {
    id: "creature-imaginary-confidant",
    label: "créature confidente imaginaire",
    kind: "creature",
    tags: ["imaginaire", "confident", "stress", "dream"],
    universes: ["fantasy", "romance", "shojo"],
    tones: ["soft", "mélancolique", "emotion"],
    styles: ["manga", "premium", "delicate"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["forme rassurante", "grands yeux attentifs", "texture onirique"],
    interactionHooks: ["écoute une confession", "pose une question miroir", "guide vers une décision"],
    environmentSignals: [],
    rarity: 2,
  },
  {
    id: "creature-lab-aberration",
    label: "aberration de laboratoire",
    kind: "creature",
    tags: ["lab", "threat", "science", "mutation"],
    universes: ["horreur", "sci-fi", "post-apocalyptique"],
    tones: ["horror", "dark", "oppressant"],
    styles: ["manga", "premium", "sharp"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["membres asymétriques", "peau translucide", "silhouette brisée"],
    interactionHooks: ["bloque une sortie", "réagit à la lumière", "laisse des traces organiques"],
    environmentSignals: [],
    rarity: 1,
  },
  {
    id: "creature-arena-beast",
    label: "bête d’arène",
    kind: "creature",
    tags: ["arena", "action", "beast", "crowd"],
    universes: ["fantasy", "shōnen", "mecha"],
    tones: ["epic", "tendu"],
    styles: ["manga", "premium", "dynamic"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["cornes marquées", "musculature lisible", "armure partielle"],
    interactionHooks: ["force un repositionnement", "charge frontalement", "met la foule en délire"],
    environmentSignals: [],
    rarity: 2,
  },
  {
    id: "creature-neon-familiar",
    label: "familier néon",
    kind: "creature",
    tags: ["city", "cyberpunk", "neon", "pet"],
    universes: ["cyberpunk", "sci-fi"],
    tones: ["cool", "tendu"],
    styles: ["manga", "stylized", "premium"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["contours luminescents", "pattes fines", "queue holographique"],
    interactionHooks: ["mène vers un raccourci", "surgit dans le champ", "observe silencieusement"],
    environmentSignals: [],
    rarity: 3,
  },
  {
    id: "creature-sand-memory-whale",
    label: "baleine-mémoire des sables",
    kind: "creature",
    tags: ["desert", "memory", "colossal", "fantasy"],
    universes: ["fantasy", "post-apocalyptique", "seinen"],
    tones: ["mélancolique", "epic", "revelation"],
    styles: ["manga", "premium", "stylized"],
    factions: [],
    weathers: ["dust", "wind"],
    worldStates: [],
    visualCues: ["corps couvert de runes", "nage dans les dunes", "œil ancien"],
    interactionHooks: ["réveille un souvenir enfoui", "déforme l’horizon", "impose le silence"],
    environmentSignals: ["sillage sableux", "vibrations du sol"],
    rarity: 4,
  },
  {
    id: "creature-glass-moth-swarm",
    label: "essaim de papillons de verre",
    kind: "creature",
    tags: ["swarm", "glass", "romance", "mystic"],
    universes: ["fantasy", "shojo", "romance"],
    tones: ["soft", "emotion", "revelation"],
    styles: ["manga", "delicate", "premium"],
    factions: [],
    weathers: ["clear", "mist"],
    worldStates: [],
    visualCues: ["ailes translucides", "reflets pastel", "traînées lumineuses"],
    interactionHooks: ["encadre une confession", "réagit à l’émotion", "transforme l’air autour des héros"],
    environmentSignals: ["éclats fins", "poussière lumineuse"],
    rarity: 3,
  },
  {
    id: "creature-sewer-crawler",
    label: "rampant des égouts",
    kind: "creature",
    tags: ["sewer", "urban", "horror", "threat"],
    universes: ["cyberpunk", "horreur", "seinen"],
    tones: ["dark", "horror", "tendu"],
    styles: ["manga", "premium", "sharp"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["dos segmenté", "mâchoire humide", "membres repliés"],
    interactionHooks: ["surgit d’une grille", "coupe une retraite", "oblige à grimper"],
    environmentSignals: ["eau sale remuée", "cliquetis dans l’ombre"],
    rarity: 2,
  },
  {
    id: "creature-rooftop-kite-spirit",
    label: "esprit-cerf-volant du toit",
    kind: "creature",
    tags: ["school", "rooftop", "spirit", "wind"],
    universes: ["shojo", "fantasy", "slice_of_life"],
    tones: ["soft", "warm", "emotion"],
    styles: ["manga", "delicate", "premium"],
    factions: [],
    weathers: ["wind", "clear"],
    worldStates: [],
    visualCues: ["corps de tissu vivant", "queue aérienne", "mouvement léger"],
    interactionHooks: ["répond au doute du héros", "oriente le regard vers le ciel", "symbolise le lâcher-prise"],
    environmentSignals: ["courants d’air visibles", "ombre mouvante sur le béton"],
    rarity: 4,
  },
  {
    id: "creature-mecha-core-wisp",
    label: "lueur de noyau mécanique",
    kind: "creature",
    tags: ["mecha", "energy", "pit", "core"],
    universes: ["mecha", "sci-fi", "shōnen"],
    tones: ["epic", "tendu", "dramatic"],
    styles: ["manga", "dynamic", "premium"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["cœur lumineux fragmenté", "traînées électriques", "forme quasi abstraite"],
    interactionHooks: ["réactive une machine", "répond au pilote choisi", "transforme la tension en spectacle"],
    environmentSignals: ["étincelles orbitales", "résonance métallique"],
    rarity: 3,
  },
  {
    id: "creature-dragon-ryuu",
    label: "dragon / ryuu",
    kind: "creature",
    tags: ["ancient", "power", "sky", "fire"],
    universes: ["fantasy", "shōnen", "historical", "supernatural"],
    tones: ["épique", "oppressant", "révélation"],
    styles: ["manga", "premium", "dynamic"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["écailles aux reflets métalliques", "envergure qui occulte le ciel", "pupille verticale immobile"],
    interactionHooks: ["atterrit entre deux factions", "parle ou pas en fixant le héros", "révèle avoir attendu cette rencontre"],
    environmentSignals: [],
    rarity: 1,
  },
  {
    id: "creature-oni-demon",
    label: "oni / démon",
    kind: "creature",
    tags: ["demon", "rage", "folklore"],
    universes: ["supernatural", "fantasy", "horreur", "historical"],
    tones: ["dark", "brutal", "horror"],
    styles: ["manga", "premium", "sharp"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["corne(s) asymétriques", "peau hors gamme chromatique naturelle", "taille déformante selon l'émotion"],
    interactionHooks: ["fixe une loi magique que personne ne comprend avant qu'il soit tard", "s'incline devant quelqu'un d'inattendu", "montre une humanité fugace"],
    environmentSignals: [],
    rarity: 1,
  },
  {
    id: "creature-shinigami",
    label: "shinigami / faucheur",
    kind: "creature",
    tags: ["death", "fate", "supernatural"],
    universes: ["supernatural", "seinen", "horreur"],
    tones: ["mélancolique", "dark", "mystérieux"],
    styles: ["manga", "premium", "delicate"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["présence perceptible avant d'être visible", "vêtements noirs aux bords flous", "ne projette pas d'ombre"],
    interactionHooks: ["vient pour quelqu'un mais repart sans lui", "pose une question à laquelle le héros ne s'attendait pas", "laisse un choix dont une seule option est mortelle"],
    environmentSignals: [],
    rarity: 1,
  },
  {
    id: "creature-golem-automaton",
    label: "golem / automate",
    kind: "creature",
    tags: ["construct", "protection", "mystery"],
    universes: ["fantasy", "steampunk", "sci-fi", "historical"],
    tones: ["épique", "mystérieux", "mélancolique"],
    styles: ["manga", "premium", "clean"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["rune ou symbole gravé sur le front", "mouvements mécaniques mais regard presque humain", "cicatrice de réparation ancienne"],
    interactionHooks: ["obéit à un ordre donné il y a des siècles", "refuse d'attaquer quelqu'un précis", "s'arrête net quand on lui parle dans une langue oubliée"],
    environmentSignals: [],
    rarity: 2,
  },
  {
    id: "creature-kaiju-titan",
    label: "titan / kaiju",
    kind: "creature",
    tags: ["colossal", "disaster", "awe"],
    universes: ["mecha", "shōnen", "post-apocalyptique", "sci-fi"],
    tones: ["épique", "oppressant", "brutal"],
    styles: ["manga", "premium", "dynamic"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["silhouette qui dépasse l'horizon", "chaque pas crée un séisme local", "biologie inclassable"],
    interactionHooks: ["ignore complètement les personnages au sol", "réagit à un son ou signal précis", "révèle une blessure ancienne encore ouverte"],
    environmentSignals: [],
    rarity: 1,
  },
  {
    id: "creature-spectre-shadow",
    label: "spectre / bête-ombre",
    kind: "creature",
    tags: ["shadow", "fear", "horror", "intangible"],
    universes: ["horreur", "supernatural", "dark_fantasy"],
    tones: ["horror", "dark", "oppressant"],
    styles: ["manga", "premium", "sharp"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["forme qui imite celle de celui qui le regarde", "froid perceptible à 3 mètres", "seuls les yeux sont nets"],
    interactionHooks: ["prend la forme d'une peur spécifique à chaque personnage", "disparaît dans la lumière directe", "laisse une marque physique sur ceux qu'il touche"],
    environmentSignals: [],
    rarity: 1,
  },
  {
    id: "creature-evolving-familiar",
    label: "familier évolutif",
    kind: "creature",
    tags: ["bond", "growth", "companion"],
    universes: ["shōnen", "fantasy", "isekai"],
    tones: ["épique", "soft", "dynamique"],
    styles: ["manga", "premium"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["marque qui évolue avec le lien affectif", "forme initiale modeste qui révèle sa vraie nature progressivement"],
    interactionHooks: ["évolue visuellement à un moment narratif clé", "réagit aux émotions du héros avant que celui-ci les exprime", "peut communiquer uniquement avec le héros"],
    environmentSignals: [],
    rarity: 2,
  },
  {
    id: "creature-parasite-symbiote",
    label: "parasite / symbiote",
    kind: "creature",
    tags: ["body-horror", "dual", "transformation"],
    universes: ["horreur", "sci-fi", "dark_fantasy", "seinen"],
    tones: ["dark", "horror", "oppressant"],
    styles: ["manga", "premium", "sharp"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["intégration visible à la peau ou aux membres", "mouvement autonome par rapport à l'hôte", "communication non-verbale avec l'hôte"],
    interactionHooks: ["prend le contrôle dans un moment de faiblesse", "protège l'hôte d'une menace sans qu'on lui demande", "révèle une mémoire ou connaissance de l'hôte inattendue"],
    environmentSignals: [],
    rarity: 1,
  },
  {
    id: "creature-ancestral-guardian",
    label: "gardien ancestral",
    kind: "creature",
    tags: ["ancient", "duty", "sealed"],
    universes: ["fantasy", "historical", "supernatural", "seinen"],
    tones: ["mélancolique", "épique", "révélation"],
    styles: ["manga", "premium"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["architecture vivante — les pierres font partie du corps", "âge impossible à estimer", "cicatrice de bataille ancienne figée à jamais"],
    interactionHooks: ["ne peut quitter un périmètre défini", "reconnaît un signe ou objet porté par le héros", "révèle avoir attendu ce moment depuis des siècles"],
    environmentSignals: [],
    rarity: 1,
  },
];

function scoreCreature(entry: OntologyEntry, input: SceneBlueprintInput) {
  const text = `${input.narrative.sceneSummary} ${input.narrative.panelIntent}`.toLowerCase();
  let score = 0;
  if (entry.universes.some((u) => input.style.universe.toLowerCase().includes(u.toLowerCase()))) score += 4;
  if (entry.tones.some((t) => input.style.tone.toLowerCase().includes(t.toLowerCase()))) score += 2;
  if (entry.tags.some((t) => text.includes(t.toLowerCase()) || input.scene.location.toLowerCase().includes(t.toLowerCase()))) score += 3;
  if (input.controls.visualExoticism >= 60) score += 2;
  return score;
}

export function generateCreatureSelection(input: SceneBlueprintInput, seed: number): ProceduralEntity[] {
  const rng = createSeededRng(seed);
  const ranked = [...CREATURE_ONTOLOGY]
    .map((entry) => ({ entry, score: scoreCreature(entry, input) }))
    .filter((item) => item.score > 0)
    .sort((a, b) => b.score - a.score);
  const desired = input.controls.visualExoticism >= 70 ? 2 : input.cast.creatureNames.length > 0 ? 1 : 0;
  return desired === 0
    ? []
    : rng.pickMany(ranked.slice(0, Math.min(ranked.length, desired + 1)), desired).map(({ entry }) => ({
        id: `${entry.id}-${seed}`,
        label: entry.label,
        kind: "creature",
        visualCues: entry.visualCues,
        interactionHooks: entry.interactionHooks,
        sourceOntologyId: entry.id,
      }));
}
