import type { OntologyEntry, ProceduralEntity, SceneBlueprintInput } from "./types";
import { createSeededRng } from "./seeded-rng";

export const NPC_ONTOLOGY: OntologyEntry[] = [
  {
    id: "npc-scavenger-broker",
    label: "broker récupérateur",
    kind: "npc",
    role: "broker",
    tags: ["street", "trade", "survival"],
    universes: ["post-apocalyptique", "cyberpunk", "seinen"],
    tones: ["dark", "tendu", "brutal"],
    styles: ["manga", "gritty", "premium"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["sac de pièces détachées", "gants usés", "regard opportuniste"],
    interactionHooks: ["marchande une info", "évalue un objet rare", "observe la tension monter"],
    environmentSignals: [],
    rarity: 2,
  },
  {
    id: "npc-arena-bookmaker",
    label: "bookmaker d’arène",
    kind: "npc",
    role: "bookmaker",
    tags: ["arena", "crowd", "money"],
    universes: ["shōnen", "seinen", "fantasy"],
    tones: ["epic", "tendu"],
    styles: ["manga", "dynamic"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["ardoise de paris", "sourire carnassier", "veste voyante"],
    interactionHooks: ["chauffe la foule", "provoque les héros", "annonce une cote absurde"],
    environmentSignals: [],
    rarity: 2,
  },
  {
    id: "npc-garden-attendant",
    label: "gardien de jardin",
    kind: "npc",
    role: "attendant",
    tags: ["garden", "romance", "quiet"],
    universes: ["romance", "fantasy", "shojo"],
    tones: ["soft", "mélancolique"],
    styles: ["manga", "delicate"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["sécateur ancien", "tablier de jardin", "posture discrète"],
    interactionHooks: ["préserve un secret du lieu", "interrompt doucement la scène", "révèle un détail floral"],
    environmentSignals: [],
    rarity: 3,
  },
  {
    id: "npc-lab-survivor",
    label: "survivant du laboratoire",
    kind: "npc",
    role: "witness",
    tags: ["lab", "fear", "science"],
    universes: ["sci-fi", "horreur", "post-apocalyptique"],
    tones: ["dark", "oppressant", "horror"],
    styles: ["manga", "clean", "premium"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["blouse déchirée", "badge fissuré", "tremblements visibles"],
    interactionHooks: ["pointe la menace", "déclenche une alarme", "laisse tomber une preuve"],
    environmentSignals: [],
    rarity: 1,
  },
  {
    id: "npc-cyberpunk-passerby",
    label: "passant augmenté",
    kind: "npc",
    role: "passerby",
    tags: ["city", "neon", "street"],
    universes: ["cyberpunk", "sci-fi", "seinen"],
    tones: ["tendu", "cool"],
    styles: ["manga", "stylized", "premium"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["implant lumineux", "capuche mouillée", "parapluie transparent"],
    interactionHooks: ["se retourne vers le héros", "évite une zone dangereuse", "sert de témoin visuel"],
    environmentSignals: [],
    rarity: 4,
  },
  {
    id: "npc-desert-cartographer",
    label: "cartographe des dunes",
    kind: "npc",
    role: "guide",
    tags: ["wasteland", "desert", "maps", "survival"],
    universes: ["post-apocalyptique", "fantasy", "seinen"],
    tones: ["brutal", "mélancolique", "epic"],
    styles: ["manga", "gritty", "premium"],
    factions: [],
    weathers: ["dust", "wind"],
    worldStates: [],
    visualCues: ["cape sableuse", "cartes roulées", "lunettes fendues"],
    interactionHooks: ["indique une route risquée", "prévient d'une zone morte", "lit les traces du vent"],
    environmentSignals: ["balises rouillées", "empreintes anciennes"],
    rarity: 3,
  },
  {
    id: "npc-shrine-medium",
    label: "médium du sanctuaire",
    kind: "npc",
    role: "oracle",
    tags: ["shrine", "spirit", "mystic", "fantasy"],
    universes: ["fantasy", "shojo", "romance"],
    tones: ["soft", "mélancolique", "emotion"],
    styles: ["manga", "delicate", "premium"],
    factions: [],
    weathers: ["mist", "clear"],
    worldStates: [],
    visualCues: ["manches longues brodées", "clochettes suspendues", "regard apaisé"],
    interactionHooks: ["interprète un présage", "guide une confession", "révèle une vérité intime"],
    environmentSignals: ["papiers votifs", "lumière tamisée"],
    rarity: 3,
  },
  {
    id: "npc-mecha-pit-engineer",
    label: "ingénieur de fosse",
    kind: "npc",
    role: "engineer",
    tags: ["mecha", "arena", "repair", "metal"],
    universes: ["mecha", "sci-fi", "shōnen"],
    tones: ["epic", "tendu", "dramatic"],
    styles: ["manga", "dynamic", "premium"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["combinaison huilée", "outil magnétique", "visage noirci"],
    interactionHooks: ["répare sous pression", "signale une faiblesse mécanique", "pousse le héros à repartir"],
    environmentSignals: ["étincelles", "rails de maintenance"],
    rarity: 2,
  },
  {
    id: "npc-school-rooftop-friend",
    label: "ami du toit d’école",
    kind: "npc",
    role: "friend",
    tags: ["school", "rooftop", "slice", "emotion"],
    universes: ["shojo", "romance", "slice_of_life"],
    tones: ["soft", "warm", "emotion"],
    styles: ["manga", "delicate", "premium"],
    factions: [],
    weathers: ["clear", "wind"],
    worldStates: [],
    visualCues: ["uniforme froissé", "boisson en canette", "posture hésitante"],
    interactionHooks: ["pose la vraie question", "couvre un mensonge", "observe le ciel avec le héros"],
    environmentSignals: ["grillage du toit", "lumière d’après-cours"],
    rarity: 4,
  },
  {
    id: "npc-underground-medic",
    label: "médecin clandestin",
    kind: "npc",
    role: "medic",
    tags: ["clinic", "injury", "survival", "dark"],
    universes: ["cyberpunk", "post-apocalyptique", "seinen"],
    tones: ["dark", "tendu", "brutal"],
    styles: ["manga", "clean", "premium"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["mallette scellée", "gants tachés", "lampe froide"],
    interactionHooks: ["stabilise une blessure", "exige un prix moral", "cache un fugitif"],
    environmentSignals: ["rideau plastique", "odeur antiseptique"],
    rarity: 2,
  },
  {
    id: "npc-mentor-sensei",
    label: "maître / sensei",
    kind: "npc",
    role: "mentor",
    tags: ["training", "wisdom", "authority"],
    universes: ["shōnen", "seinen", "martial_arts", "fantasy"],
    tones: ["epic", "tendu", "mélancolique"],
    styles: ["manga", "premium"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["cicatrice ancienne", "regard perçant", "tenue sobre et usée", "mains calleuses"],
    interactionHooks: ["révèle une technique interdite", "teste la détermination du héros", "cache une douleur passée"],
    environmentSignals: [],
    rarity: 2,
  },
  {
    id: "npc-villain-recurring",
    label: "antagoniste récurrent",
    kind: "npc",
    role: "villain",
    tags: ["threat", "philosophy", "opposition"],
    universes: ["shōnen", "seinen", "fantasy", "sci-fi"],
    tones: ["dark", "epic", "oppressant"],
    styles: ["manga", "premium", "sharp"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["tenue distinctive aux couleurs inversées du héros", "sourire ambigu", "marque ou cicatrice iconique"],
    interactionHooks: ["propose un marché impossible", "révèle une vérité que le héros refuse", "épargne le héros sans explication"],
    environmentSignals: [],
    rarity: 1,
  },
  {
    id: "npc-rival-friendly",
    label: "rival / partenaire ambigu",
    kind: "npc",
    role: "rival",
    tags: ["competition", "respect", "growth"],
    universes: ["shōnen", "sport", "mecha", "fantasy"],
    tones: ["épique", "tendu", "dynamique"],
    styles: ["manga", "dynamic", "premium"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["tenue miroir du héros mais différente", "expression hautaine ou souriante selon contexte"],
    interactionHooks: ["défie le héros au mauvais moment", "arrive en renfort inattendu", "révèle une faiblesse commune"],
    environmentSignals: [],
    rarity: 2,
  },
  {
    id: "npc-love-interest",
    label: "intérêt romantique",
    kind: "npc",
    role: "love_interest",
    tags: ["romance", "emotion", "anchor"],
    universes: ["shōjo", "shōnen", "slice_of_life", "seinen"],
    tones: ["romantique", "mélancolique", "soft"],
    styles: ["manga", "delicate", "premium"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["détail distinctif mémorisé par le héros", "expression retenue qui cache l'émotion"],
    interactionHooks: ["apparaît à un moment de vulnérabilité", "pose la question que personne n'ose", "s'éloigne sans explication"],
    environmentSignals: [],
    rarity: 2,
  },
  {
    id: "npc-informant",
    label: "informateur / espion",
    kind: "npc",
    role: "informant",
    tags: ["intel", "shadow", "double-game"],
    universes: ["seinen", "thriller", "cyberpunk", "mystery"],
    tones: ["tendu", "dark", "mystérieux"],
    styles: ["manga", "gritty"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["capuche ou masque partiel", "regard fuyant", "mains toujours dissimulées"],
    interactionHooks: ["vend une info avec une clause cachée", "disparaît avant la fin de la scène", "laisse un message codé"],
    environmentSignals: [],
    rarity: 2,
  },
  {
    id: "npc-oracle",
    label: "oracle / prophète",
    kind: "npc",
    role: "oracle",
    tags: ["prophecy", "mystery", "fate"],
    universes: ["fantasy", "supernatural", "historical"],
    tones: ["mystérieux", "mélancolique", "oppressant"],
    styles: ["manga", "premium"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["yeux voilés ou hors normes", "vêtements anciens ou déchirés", "attitude détachée du présent"],
    interactionHooks: ["prédit quelque chose d'ambigu", "parle du futur comme du passé", "refuse de préciser ce qu'il sait"],
    environmentSignals: [],
    rarity: 1,
  },
  {
    id: "npc-corrupt-official",
    label: "fonctionnaire corrompu",
    kind: "npc",
    role: "antagonist_minor",
    tags: ["authority", "corruption", "obstacle"],
    universes: ["seinen", "historical", "political", "fantasy"],
    tones: ["tendu", "dark", "politique"],
    styles: ["manga", "clean", "premium"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["uniforme immaculé mais regard calculateur", "sourire de façade", "mains jointes sur un bureau"],
    interactionHooks: ["impose une règle arbitraire", "monnaye une faveur", "retourne sa veste au mauvais moment"],
    environmentSignals: [],
    rarity: 3,
  },
  {
    id: "npc-berserker",
    label: "guerrier berserker",
    kind: "npc",
    role: "wild_card",
    tags: ["combat", "rage", "unpredictable"],
    universes: ["shōnen", "fantasy", "dark_fantasy", "seinen"],
    tones: ["brutal", "épique", "dark"],
    styles: ["manga", "dynamic", "premium", "sharp"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["cicatrices multiples", "yeux vides dans la rage", "arme démesurée ou mains nues"],
    interactionHooks: ["frappe ami et ennemi sans distinction", "s'arrête soudainement sans raison apparente", "protège quelqu'un de façon inattendue"],
    environmentSignals: [],
    rarity: 2,
  },
  {
    id: "npc-child-witness",
    label: "enfant témoin",
    kind: "npc",
    role: "witness",
    tags: ["innocence", "trauma", "catalyst"],
    universes: ["seinen", "horreur", "post-apocalyptique", "drame"],
    tones: ["mélancolique", "dark", "oppressant"],
    styles: ["manga", "clean"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["grand objet qu'il serre fort", "regard fixé sur un point hors champ", "vêtements trop grands"],
    interactionHooks: ["dit une vérité que les adultes refusent d'entendre", "reconnaît quelqu'un que personne d'autre n'attendait", "pleure en silence"],
    environmentSignals: [],
    rarity: 2,
  },
  {
    id: "npc-healer",
    label: "soignant / médecin de campagne",
    kind: "npc",
    role: "support",
    tags: ["care", "knowledge", "moral"],
    universes: ["médical", "fantasy", "post-apocalyptique", "shōnen"],
    tones: ["mélancolique", "épique", "drame"],
    styles: ["manga", "clean", "premium"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["mains toujours propres malgré le chaos", "sac de matériel médical", "fatigue profonde"],
    interactionHooks: ["sauve quelqu'un contre toute attente", "annonce une mauvaise nouvelle calmement", "pose des limites éthiques"],
    environmentSignals: [],
    rarity: 3,
  },
  {
    id: "npc-alchemist",
    label: "alchimiste / inventeur",
    kind: "npc",
    role: "enabler",
    tags: ["science", "magic", "eccentric"],
    universes: ["fantasy", "steampunk", "sci-fi", "seinen"],
    tones: ["mystérieux", "humoristique", "épique"],
    styles: ["manga", "premium"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["lunettes de protection relevées", "taches indéfinissables sur la blouse", "atelier en désordre calculé"],
    interactionHooks: ["remet un objet dont le vrai rôle se révèle plus tard", "refuse d'expliquer comment ça marche", "fait exploser quelque chose au mauvais moment"],
    environmentSignals: [],
    rarity: 2,
  },
  {
    id: "npc-crowd-leader",
    label: "meneur de foule",
    kind: "npc",
    role: "catalyst",
    tags: ["crowd", "politics", "emotion"],
    universes: ["seinen", "historical", "political", "shōnen"],
    tones: ["épique", "tendu", "politique"],
    styles: ["manga", "dynamic"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["position surélevée", "geste large vers la foule", "voix qui porte sans hurler"],
    interactionHooks: ["retourne l'opinion au mauvais moment", "désigne le héros comme symbole", "déclenche une émeute ou un silence"],
    environmentSignals: [],
    rarity: 3,
  },
  {
    id: "npc-deserter",
    label: "soldat déserteur",
    kind: "npc",
    role: "runaway",
    tags: ["war", "trauma", "moral"],
    universes: ["seinen", "historical", "post-apocalyptique", "dark_fantasy"],
    tones: ["mélancolique", "dark", "tendu"],
    styles: ["manga", "gritty"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["uniforme lacéré dont il a retiré les insignes", "regard qui surveille constamment les sorties"],
    interactionHooks: ["connaît un passage secret dans la zone de conflit", "refuse de reprendre une arme puis le fait malgré lui", "reconnaît quelqu'un qu'il pensait mort"],
    environmentSignals: [],
    rarity: 2,
  },
  {
    id: "npc-ghost-lingering",
    label: "esprit attardé / fantôme visible",
    kind: "npc",
    role: "ghost",
    tags: ["death", "memory", "supernatural"],
    universes: ["supernatural", "horreur", "seinen", "slice_of_life"],
    tones: ["mélancolique", "horror", "mystérieux"],
    styles: ["manga", "premium", "delicate"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["légèrement transparent ou décalé par rapport au décor", "vêtements de l'époque de sa mort", "ne touche pas vraiment les objets"],
    interactionHooks: ["apparaît uniquement à un personnage spécifique", "répète en boucle un dernier acte inachevé", "disparaît quand on le regarde trop longtemps"],
    environmentSignals: [],
    rarity: 1,
  },
  {
    id: "npc-street-fighter",
    label: "combattant de rue",
    kind: "npc",
    role: "challenger",
    tags: ["fight", "street", "pride"],
    universes: ["shōnen", "sport", "seinen"],
    tones: ["brutal", "épique", "dynamique"],
    styles: ["manga", "dynamic", "sharp"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["bandages aux mains", "cicatrices récentes", "position de garde naturelle"],
    interactionHooks: ["défie sans prévenir", "demande une revanche après une défaite", "révèle une loyauté inattendue"],
    environmentSignals: [],
    rarity: 3,
  },
  {
    id: "npc-cyberpunk-fixer",
    label: "fixeur cyberpunk",
    kind: "npc",
    role: "broker",
    tags: ["deal", "network", "city"],
    universes: ["cyberpunk", "sci-fi", "seinen"],
    tones: ["cool", "tendu", "dark"],
    styles: ["manga", "stylized", "premium"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["implants visibles discrets", "hologramme projeté depuis la paume", "toujours dans un endroit à plusieurs sorties"],
    interactionHooks: ["propose un contrat trop propre pour être honnête", "révèle qu'il sait déjà ce que le héros veut", "disparaît quand la situation dégénère"],
    environmentSignals: [],
    rarity: 2,
  },
  {
    id: "npc-cultist",
    label: "adepte de culte",
    kind: "npc",
    role: "zealot",
    tags: ["cult", "fanaticism", "horror"],
    universes: ["horreur", "supernatural", "dark_fantasy"],
    tones: ["horror", "dark", "oppressant"],
    styles: ["manga", "premium", "sharp"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["marque ou tatouage rituel visible", "calme inquiétant", "sourire qui ne correspond pas à la situation"],
    interactionHooks: ["cite un dogme qui contient une vérité déformée", "se sacrifie sans hésitation", "reconnaît le héros comme celui qui était prédit"],
    environmentSignals: [],
    rarity: 2,
  },
  {
    id: "npc-guard-soldier",
    label: "garde / soldat",
    kind: "npc",
    role: "guard",
    tags: [
      "guard",
      "garde",
      "soldat",
      "military",
      "patrol",
      "protection",
      "security",
      "sentinel",
      "watchtower",
      "checkpoint",
      "door",
      "entrance",
      "authority",
    ],
    universes: ["fantasy", "historical", "seinen", "shōnen", "sci-fi", "dark_fantasy"],
    tones: ["tendu", "brutal", "épique", "oppressant"],
    styles: ["manga", "premium", "dynamic"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: [
      "armure ou uniforme réglementaire",
      "arme visible en position neutre",
      "regard qui scrute sans relâche",
      "posture immobile ou rythmée",
    ],
    interactionHooks: [
      "bloque le passage et demande les papiers",
      "tourne le dos au mauvais moment",
      "reconnaît quelqu'un dans le groupe",
    ],
    environmentSignals: [],
    rarity: 3,
  },
  {
    id: "npc-thief-pickpocket",
    label: "voleur / pickpocket",
    kind: "npc",
    role: "thief",
    tags: ["voleur", "thief", "pickpocket", "steal", "rogue", "shadow", "escape", "market", "crowd", "alley", "ruelle", "discret"],
    universes: ["fantasy", "seinen", "shōnen", "historical", "cyberpunk"],
    tones: ["tendu", "cool", "humoristique"],
    styles: ["manga", "dynamic", "gritty"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: [
      "capuche ou foulard dissimulant le visage",
      "mains toujours actives",
      "regard qui calcule les distances",
      "poches et sacoches multiples",
    ],
    interactionHooks: [
      "subtilise un objet clé sans que personne le remarque",
      "propose un marché en échange d'une info",
      "fuit en laissant tomber quelque chose d'important",
    ],
    environmentSignals: [],
    rarity: 3,
  },
  {
    id: "npc-field-doctor",
    label: "médecin de terrain",
    kind: "npc",
    role: "medic",
    tags: ["médecin", "doctor", "médical", "soins", "blessé", "heal", "hospital", "infirmerie", "emergency", "trauma", "blessure", "sang"],
    universes: ["médical", "post-apocalyptique", "seinen", "shōnen", "historical"],
    tones: ["mélancolique", "tendu", "épique"],
    styles: ["manga", "clean", "premium"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["blouse ou bandages visibles", "trousse médicale à portée", "fatigue profonde dans le regard", "mains précises et assurées"],
    interactionHooks: ["stabilise un blessé en pleine action", "pose un diagnostic brutal mais juste", "manque de matériel au pire moment"],
    environmentSignals: [],
    rarity: 3,
  },
  {
    id: "npc-merchant-vendor",
    label: "marchand / vendeur",
    kind: "npc",
    role: "merchant",
    tags: [
      "marchand",
      "merchant",
      "vendeur",
      "vendor",
      "boutique",
      "shop",
      "commerce",
      "marché",
      "market",
      "trade",
      "acheter",
      "vendre",
      "prix",
    ],
    universes: ["fantasy", "historical", "shōnen", "isekai", "cyberpunk"],
    tones: ["humoristique", "cool", "mélancolique"],
    styles: ["manga", "premium", "clean"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: [
      "étal chargé de marchandises improbables",
      "sourire commercial inflexible",
      "abaque ou tablette de prix",
      "accent ou dialecte régional prononcé",
    ],
    interactionHooks: [
      "propose exactement ce dont le héros a besoin, au mauvais prix",
      "connaît une information rare sur le lieu",
      "reconnaît une pièce ou objet que le héros porte",
    ],
    environmentSignals: [],
    rarity: 4,
  },
  {
    id: "npc-priest-monk",
    label: "prêtre / moine",
    kind: "npc",
    role: "cleric",
    tags: ["prêtre", "priest", "moine", "monk", "temple", "religion", "culte", "foi", "bénédiction", "malédiction", "rituel", "sacré", "divin"],
    universes: ["fantasy", "historical", "supernatural", "dark_fantasy", "seinen"],
    tones: ["mystérieux", "mélancolique", "oppressant"],
    styles: ["manga", "premium"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["robe ou habit religieux", "symbole sacré visible", "calme absolu même dans le chaos", "voix douce qui porte"],
    interactionHooks: ["bénit ou maudit sans demander l'avis", "connaît un secret du lieu saint", "pose une question à laquelle personne n'avait pensé"],
    environmentSignals: [],
    rarity: 2,
  },
  {
    id: "npc-civilian-peasant",
    label: "civil / paysan",
    kind: "npc",
    role: "civilian",
    tags: ["civil", "civilian", "paysan", "peasant", "villageois", "villager", "habitant", "passant", "témoin", "foule", "people", "everyday"],
    universes: ["fantasy", "historical", "shōnen", "slice_of_life", "post-apocalyptique"],
    tones: ["mélancolique", "drame", "soft"],
    styles: ["manga", "clean"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["vêtements usés mais soignés", "regard fuyant ou hébété", "geste de protection instinctif", "outil de travail à la main"],
    interactionHooks: ["montre le chemin sans comprendre les enjeux", "révèle une rumeur locale qui se révèle vraie", "fuit en abandonnant un objet important"],
    environmentSignals: [],
    rarity: 5,
  },
  {
    id: "npc-assassin-hitman",
    label: "assassin / tueur à gages",
    kind: "npc",
    role: "assassin",
    tags: ["assassin", "tueur", "hitman", "killer", "shadow", "target", "contract", "blade", "poison", "silent", "discret", "embuscade"],
    universes: ["seinen", "shōnen", "thriller", "dark_fantasy", "cyberpunk", "historical"],
    tones: ["tendu", "dark", "brutal"],
    styles: ["manga", "premium", "sharp"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: [
      "silhouette qui n'attire pas l'attention jusqu'au dernier moment",
      "arme dissimulée mais accessible",
      "regard vide qui évalue les cibles",
    ],
    interactionHooks: [
      "rate sa cible pour une raison inexpliquée",
      "propose de changer de camp si le prix est juste",
      "révèle qui l'a engagé avant de disparaître",
    ],
    environmentSignals: [],
    rarity: 1,
  },
];

function matchScore(entry: OntologyEntry, input: SceneBlueprintInput) {
  const haystacks = [
    input.style.universe.toLowerCase(),
    input.style.tone.toLowerCase(),
    input.scene.location.toLowerCase(),
    input.narrative.sceneSummary.toLowerCase(),
  ];
  let score = 0;
  if (entry.universes.some((u) => haystacks[0].includes(u.toLowerCase()))) score += 4;
  if (entry.tones.some((t) => haystacks[1].includes(t.toLowerCase()))) score += 3;
  if (entry.tags.some((t) => haystacks[2].includes(t.toLowerCase()) || haystacks[3].includes(t.toLowerCase()))) score += 2;
  score += Math.max(0, 6 - entry.rarity);
  return score;
}

export function generateNpcSelection(
  input: SceneBlueprintInput,
  seed: number,
): ProceduralEntity[] {
  const rng = createSeededRng(seed);
  const ranked = [...NPC_ONTOLOGY]
    .map((entry) => ({ entry, score: matchScore(entry, input) }))
    .filter((item) => item.score > 0)
    .sort((a, b) => b.score - a.score);
  const desired = input.controls.npcVariety >= 70 ? 3 : input.controls.npcVariety >= 40 ? 2 : 1;
  const candidatePool = ranked.slice(0, Math.min(ranked.length, desired + 2));
  return rng.pickMany(candidatePool, desired).map(({ entry }) => ({
    id: `${entry.id}-${seed}`,
    label: entry.label,
    kind: "npc",
    role: entry.role,
    visualCues: entry.visualCues,
    interactionHooks: entry.interactionHooks,
    sourceOntologyId: entry.id,
  }));
}
