import type { OntologyEntry, ProceduralEntity, SceneBlueprintInput } from "./types";
import { createSeededRng } from "./seeded-rng";

export const NPC_ONTOLOGY: OntologyEntry[] = [
  {
    id: "npc-scavenger-broker",
    label: "broker récupérateur",
    kind: "npc",
    role: "broker",
    tags: ["street", "trade", "survival"],
    universes: ["post-apocalyptique", "cyberpunk", "seinen"],
    tones: ["dark", "tendu", "brutal"],
    styles: ["manga", "gritty", "premium"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["sac de pièces détachées", "gants usés", "regard opportuniste"],
    interactionHooks: ["marchande une info", "évalue un objet rare", "observe la tension monter"],
    environmentSignals: [],
    rarity: 2,
  },
  {
    id: "npc-arena-bookmaker",
    label: "bookmaker d’arène",
    kind: "npc",
    role: "bookmaker",
    tags: ["arena", "crowd", "money"],
    universes: ["shōnen", "seinen", "fantasy"],
    tones: ["epic", "tendu"],
    styles: ["manga", "dynamic"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["ardoise de paris", "sourire carnassier", "veste voyante"],
    interactionHooks: ["chauffe la foule", "provoque les héros", "annonce une cote absurde"],
    environmentSignals: [],
    rarity: 2,
  },
  {
    id: "npc-garden-attendant",
    label: "gardien de jardin",
    kind: "npc",
    role: "attendant",
    tags: ["garden", "romance", "quiet"],
    universes: ["romance", "fantasy", "shojo"],
    tones: ["soft", "mélancolique"],
    styles: ["manga", "delicate"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["sécateur ancien", "tablier de jardin", "posture discrète"],
    interactionHooks: ["préserve un secret du lieu", "interrompt doucement la scène", "révèle un détail floral"],
    environmentSignals: [],
    rarity: 3,
  },
  {
    id: "npc-lab-survivor",
    label: "survivant du laboratoire",
    kind: "npc",
    role: "witness",
    tags: ["lab", "fear", "science"],
    universes: ["sci-fi", "horreur", "post-apocalyptique"],
    tones: ["dark", "oppressant", "horror"],
    styles: ["manga", "clean", "premium"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["blouse déchirée", "badge fissuré", "tremblements visibles"],
    interactionHooks: ["pointe la menace", "déclenche une alarme", "laisse tomber une preuve"],
    environmentSignals: [],
    rarity: 1,
  },
  {
    id: "npc-cyberpunk-passerby",
    label: "passant augmenté",
    kind: "npc",
    role: "passerby",
    tags: ["city", "neon", "street"],
    universes: ["cyberpunk", "sci-fi", "seinen"],
    tones: ["tendu", "cool"],
    styles: ["manga", "stylized", "premium"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["implant lumineux", "capuche mouillée", "parapluie transparent"],
    interactionHooks: ["se retourne vers le héros", "évite une zone dangereuse", "sert de témoin visuel"],
    environmentSignals: [],
    rarity: 4,
  },
  {
    id: "npc-desert-cartographer",
    label: "cartographe des dunes",
    kind: "npc",
    role: "guide",
    tags: ["wasteland", "desert", "maps", "survival"],
    universes: ["post-apocalyptique", "fantasy", "seinen"],
    tones: ["brutal", "mélancolique", "epic"],
    styles: ["manga", "gritty", "premium"],
    factions: [],
    weathers: ["dust", "wind"],
    worldStates: [],
    visualCues: ["cape sableuse", "cartes roulées", "lunettes fendues"],
    interactionHooks: ["indique une route risquée", "prévient d'une zone morte", "lit les traces du vent"],
    environmentSignals: ["balises rouillées", "empreintes anciennes"],
    rarity: 3,
  },
  {
    id: "npc-shrine-medium",
    label: "médium du sanctuaire",
    kind: "npc",
    role: "oracle",
    tags: ["shrine", "spirit", "mystic", "fantasy"],
    universes: ["fantasy", "shojo", "romance"],
    tones: ["soft", "mélancolique", "emotion"],
    styles: ["manga", "delicate", "premium"],
    factions: [],
    weathers: ["mist", "clear"],
    worldStates: [],
    visualCues: ["manches longues brodées", "clochettes suspendues", "regard apaisé"],
    interactionHooks: ["interprète un présage", "guide une confession", "révèle une vérité intime"],
    environmentSignals: ["papiers votifs", "lumière tamisée"],
    rarity: 3,
  },
  {
    id: "npc-mecha-pit-engineer",
    label: "ingénieur de fosse",
    kind: "npc",
    role: "engineer",
    tags: ["mecha", "arena", "repair", "metal"],
    universes: ["mecha", "sci-fi", "shōnen"],
    tones: ["epic", "tendu", "dramatic"],
    styles: ["manga", "dynamic", "premium"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["combinaison huilée", "outil magnétique", "visage noirci"],
    interactionHooks: ["répare sous pression", "signale une faiblesse mécanique", "pousse le héros à repartir"],
    environmentSignals: ["étincelles", "rails de maintenance"],
    rarity: 2,
  },
  {
    id: "npc-school-rooftop-friend",
    label: "ami du toit d’école",
    kind: "npc",
    role: "friend",
    tags: ["school", "rooftop", "slice", "emotion"],
    universes: ["shojo", "romance", "slice_of_life"],
    tones: ["soft", "warm", "emotion"],
    styles: ["manga", "delicate", "premium"],
    factions: [],
    weathers: ["clear", "wind"],
    worldStates: [],
    visualCues: ["uniforme froissé", "boisson en canette", "posture hésitante"],
    interactionHooks: ["pose la vraie question", "couvre un mensonge", "observe le ciel avec le héros"],
    environmentSignals: ["grillage du toit", "lumière d’après-cours"],
    rarity: 4,
  },
  {
    id: "npc-underground-medic",
    label: "médecin clandestin",
    kind: "npc",
    role: "medic",
    tags: ["clinic", "injury", "survival", "dark"],
    universes: ["cyberpunk", "post-apocalyptique", "seinen"],
    tones: ["dark", "tendu", "brutal"],
    styles: ["manga", "clean", "premium"],
    factions: [],
    weathers: [],
    worldStates: [],
    visualCues: ["mallette scellée", "gants tachés", "lampe froide"],
    interactionHooks: ["stabilise une blessure", "exige un prix moral", "cache un fugitif"],
    environmentSignals: ["rideau plastique", "odeur antiseptique"],
    rarity: 2,
  },
];

function matchScore(entry: OntologyEntry, input: SceneBlueprintInput) {
  const haystacks = [
    input.style.universe.toLowerCase(),
    input.style.tone.toLowerCase(),
    input.scene.location.toLowerCase(),
    input.narrative.sceneSummary.toLowerCase(),
  ];
  let score = 0;
  if (entry.universes.some((u) => haystacks[0].includes(u.toLowerCase()))) score += 4;
  if (entry.tones.some((t) => haystacks[1].includes(t.toLowerCase()))) score += 3;
  if (entry.tags.some((t) => haystacks[2].includes(t.toLowerCase()) || haystacks[3].includes(t.toLowerCase()))) score += 2;
  score += Math.max(0, 6 - entry.rarity);
  return score;
}

export function generateNpcSelection(
  input: SceneBlueprintInput,
  seed: number,
): ProceduralEntity[] {
  const rng = createSeededRng(seed);
  const ranked = [...NPC_ONTOLOGY]
    .map((entry) => ({ entry, score: matchScore(entry, input) }))
    .filter((item) => item.score > 0)
    .sort((a, b) => b.score - a.score);
  const desired = input.controls.npcVariety >= 70 ? 3 : input.controls.npcVariety >= 40 ? 2 : 1;
  const candidatePool = ranked.slice(0, Math.min(ranked.length, desired + 2));
  return rng.pickMany(candidatePool, desired).map(({ entry }) => ({
    id: `${entry.id}-${seed}`,
    label: entry.label,
    kind: "npc",
    role: entry.role,
    visualCues: entry.visualCues,
    interactionHooks: entry.interactionHooks,
    sourceOntologyId: entry.id,
  }));
}
