export const RENDERING_MODES = [
  "CHARACTER_SHEET",
  "CHARACTER_EXPRESSION_SET",
  "OUTFIT_VARIATION",
  "LOCATION_KEYFRAME",
  "PANEL_DRAFT",
  "PANEL_FINAL",
  "COVER_ART",
  "INPAINT_FIX",
  "POSE_LOCK_VARIATION",
  "STYLE_TRANSFER_VARIATION",
] as const;

export type RenderingMode = (typeof RENDERING_MODES)[number];
