/* eslint-disable @typescript-eslint/no-explicit-any -- TODO(Sprint 4 / TASK-4.1): typer après split de narrative-pass.ts. */
/**
 * Promeut automatiquement les PNJ découverts dans le bundle (storyboard
 * + scènes) qui ne sont pas encore dans `rawCharacters`, en respectant la
 * policy `entityRegistry` du studio (skip si tagged temporary, promote
 * uniquement si éligible).
 *
 * Extrait depuis `narrative-pass.ts`. Mute `rawCharacters` en place.
 */

import { prisma } from "@manga-ai-studio/db";
import { logPipelineInfo } from "../../lib/pipeline-logger";
import { parseEntityRegistry } from "../../schemas/pipeline-contracts";
import {
  partitionNpcsByPolicy,
  computeDefaultForbiddenDrift,
  mapEntityKindToRoleType,
  slugifyNpcName,
} from "./npc-auto-promotion";

type LooseRecord = any;

export interface NpcPromotionRunnerInput {
  projectId: string;
  revisedBundle: LooseRecord;
  studioSnapshot: LooseRecord;
  rawCharacters: LooseRecord[];
}

export async function runNpcPromotion(input: NpcPromotionRunnerInput): Promise<void> {
  const { projectId, revisedBundle, studioSnapshot, rawCharacters } = input;

  const knownCharNames = new Set(rawCharacters.map((c: LooseRecord) => c.name.toLowerCase()));
  const bundleCharNames = new Set<string>();

  for (const page of revisedBundle.storyboard.pages) {
    for (const panel of page.panels) {
      for (const name of panel.characters ?? []) {
        if (name && !knownCharNames.has(name.toLowerCase())) {
          bundleCharNames.add(name);
        }
      }
    }
  }
  for (const scene of revisedBundle.script.scenes) {
    for (const name of scene.characters ?? []) {
      if (name && !knownCharNames.has(name.toLowerCase())) {
        bundleCharNames.add(name);
      }
    }
  }

  // P4.2 : validation Zod tolérante à la frontière — si le registry est
  // malformé, on dégrade gracefully (null) + log warn, plutôt que d'accepter
  // silencieusement un blob corrompu qui contaminerait la logique promotion.
  const entityRegistry = parseEntityRegistry(studioSnapshot?.data?.entityRegistry ?? null);
  const promotedNames = new Set<string>(
    (entityRegistry?.namedEntities ?? [])
      .filter((e) => e.promotionStatus === "promoted" || e.allowedRecurrence === "story_locked")
      .map((e) => e.name.toLowerCase()),
  );
  const temporaryNames = new Set<string>(
    [
      ...(entityRegistry?.temporaryEntities ?? []),
      ...(entityRegistry?.backgroundExtras ?? []),
    ].map((e) => e.name.toLowerCase()),
  );

  if (bundleCharNames.size === 0) return;

  // P3.1 (partiel) : helper pur extrait dans narrative/npc-auto-promotion.ts
  const { toPromote, toSkip } = partitionNpcsByPolicy({
    bundleCharNames,
    promotedNames,
    temporaryNames,
    hasEntityRegistry: Boolean(entityRegistry),
  });

  if (toSkip.length > 0) {
    logPipelineInfo("npc_discipline_skip", { count: toSkip.length, names: toSkip });
  }
  if (toPromote.length > 0) {
    logPipelineInfo("npc_promotion_create", { count: toPromote.length, names: toPromote });
  }

  // C04: hoist storyBible query outside the NPC loop
  const { resolveEntity } = await import("@manga-ai-studio/ai");
  const storyBibleForGlossary = await prisma.storyBible
    .findUnique({ where: { projectId } })
    .catch(() => null);
  const glossaryForEntities = Array.isArray(storyBibleForGlossary?.glossary)
    ? (storyBibleForGlossary.glossary as Array<{
        term: string;
        description?: string;
        visualCore?: string;
        entityKind?: string;
      }>)
    : [];

  for (const pnjName of toPromote) {
    try {
      const slug = slugifyNpcName(pnjName);
      const scenesWithPnj = revisedBundle.script.scenes.filter((s: LooseRecord) =>
        (s.characters ?? []).includes(pnjName),
      );
      const contextHint = scenesWithPnj[0]?.summary?.slice(0, 200) ?? "";
      const entityProfile = await resolveEntity({
        name: pnjName,
        contextText: contextHint,
        projectId,
        glossary: glossaryForEntities,
        projectBible: storyBibleForGlossary?.summary ?? null,
      });

      const entityRoleType = mapEntityKindToRoleType(entityProfile.entityKind);
      const defaultForbiddenDrift = computeDefaultForbiddenDrift(entityProfile.entityKind);

      const charData = {
        name: pnjName,
        roleType: entityRoleType,
        status: "alive",
        autoGenerated: true,
        forbiddenVisualDrift: defaultForbiddenDrift,
        appearance: [
          entityProfile.speciesLabel ? `${entityProfile.speciesLabel}` : null,
          entityProfile.typicalAppearance || null,
          entityProfile.canonicalVisualCore || null,
          scenesWithPnj[0]?.location ? `lié à ${scenesWithPnj[0].location}` : null,
        ]
          .filter(Boolean)
          .join(", ") || null,
        continuityProfile: {
          entityKind: entityProfile.entityKind,
          speciesLabel: entityProfile.speciesLabel,
          dialogueMode: entityProfile.dialogueMode,
          recurrencePolicy: entityProfile.recurrencePolicy,
          canonicalVisualCore: entityProfile.canonicalVisualCore,
          source: entityProfile.source,
          confidence: entityProfile.confidence,
        },
      };
      const newChar = await prisma.character.upsert({
        where: { projectId_slug: { projectId, slug } },
        create: { projectId, slug, ...charData },
        update: { autoGenerated: true, updatedAt: new Date() },
      });

      rawCharacters.push({
        id: newChar.id,
        name: pnjName,
        roleType: newChar.roleType ?? "pnj",
        objective: scenesWithPnj[0]?.summary?.slice(0, 160) ?? null,
        fear: null,
        biography: contextHint ? `PNJ introduit dans le contexte suivant : ${contextHint}` : null,
        traits: [entityProfile.typicalAppearance || "pnj récurrent"].filter(Boolean) as string[],
        flaws: [] as string[],
        gender: null,
        appearance: (newChar.appearance as string | null) ?? null,
        hairColor: null,
        eyeColor: null,
        outfitDefault: null,
        canonicalImageUrl: null,
        canonSignatureText: null,
        forbiddenVisualDrift: defaultForbiddenDrift,
        bodyDetails: null,
        wardrobeDetails: null,
        visualProfile: {},
        bodyState: {},
        wardrobeProfile: {},
        speechProfile: {},
        continuityProfile: {
          entityKind: entityProfile.entityKind,
          speciesLabel: entityProfile.speciesLabel,
          dialogueMode: entityProfile.dialogueMode,
          recurrencePolicy: entityProfile.recurrencePolicy,
          canonicalVisualCore: entityProfile.canonicalVisualCore,
          source: entityProfile.source,
          confidence: entityProfile.confidence,
          introLocation: scenesWithPnj[0]?.location ?? null,
        },
        characterFingerprint: null,
        visualRefUrls: [],
        entityKind: entityProfile.entityKind,
        speciesLabel: entityProfile.speciesLabel ?? null,
        dialogueMode: entityProfile.dialogueMode,
        recurrencePolicy: entityProfile.recurrencePolicy,
      } as LooseRecord);
      knownCharNames.add(pnjName.toLowerCase());
    } catch (e) {
      console.warn(
        `[pipeline] PNJ creation failed for "${pnjName}":`,
        e instanceof Error ? e.message : e,
      );
    }
  }
}
