/**
 * SceneExtrasRegistry: gestion des PNJ persistants par scène/location.
 * Garantit que les mêmes extras réapparaissent dans la même scène.
 */

import type { PrismaClient } from "@manga-ai-studio/db";
import type { SceneExtra, NpcType } from "@manga-ai-studio/core";

/**
 * Charge les extras existants pour une scène ou location.
 */
export async function loadSceneExtras(
  prisma: PrismaClient,
  input: {
    sceneId?: string;
    locationId?: string;
    projectId: string;
  }
): Promise<SceneExtra[]> {
  // TODO: Créer un modèle SceneExtra dans Prisma si nécessaire
  // Pour l'instant, retourner un array vide (pas de persistance DB)
  
  console.log(`[scene-extras-registry] Loading extras for scene=${input.sceneId}, location=${input.locationId}`);
  
  return [];
}

/**
 * Persiste un extra dans le registry.
 */
export async function persistSceneExtra(
  prisma: PrismaClient,
  extra: SceneExtra
): Promise<void> {
  // TODO: Créer un modèle SceneExtra dans Prisma
  console.log(`[scene-extras-registry] Persisting extra ${extra.id} (${extra.archetype})`);
  
  // Pour l'instant, pas de persistance réelle
}

/**
 * Promeut un extra en personnage narratif (Character DB).
 * Appelé quand un PNJ parle ou devient important narrativement.
 */
export async function promoteExtraToNarrativeNpc(
  prisma: PrismaClient,
  input: {
    projectId: string;
    extraId: string;
    extra: SceneExtra;
    firstDialogue?: string;
  }
): Promise<{ characterId: string; promoted: boolean }> {
  console.log(`[scene-extras-registry] Promoting extra ${input.extraId} to narrative NPC`);

  // Générer un nom pour ce PNJ (ex: "Barman", "Client 1", etc.)
  const npcName = generateNpcName(input.extra.archetype);

  // Créer un Character léger
  const character = await prisma.character.create({
    data: {
      projectId: input.projectId,
      name: npcName,
      roleType: "secondary",
      gender: input.extra.visualSignature.genderPresentation === "masculine" ? "male" : input.extra.visualSignature.genderPresentation === "feminine" ? "female" : null,
      appearance: JSON.stringify(input.extra.visualSignature),
      autoGenerated: true,
      biography: `PNJ auto-généré (${input.extra.archetype}) apparu dans la scène ${input.extra.sceneId}`,
      traits: [input.extra.archetype],
      flaws: [],
      secrets: [],
    },
  });

  return {
    characterId: character.id,
    promoted: true,
  };
}

/**
 * Détermine le type de PNJ selon son importance narrative.
 */
export function classifyNpcType(extra: SceneExtra): NpcType {
  if (extra.canSpeak) return "narrative";
  if (extra.reusePriority >= 80) return "support";
  return "ambient";
}

/**
 * Génère un nom pour un PNJ basé sur son archetype.
 */
function generateNpcName(archetype: SceneExtra["archetype"]): string {
  const names: Record<string, string> = {
    bartender: "Barman",
    client: "Client",
    guard: "Garde",
    server: "Serveur",
    merchant: "Marchand",
    passerby: "Passant",
    crowd: "Figurant",
    other: "PNJ",
  };
  
  const base = names[archetype] ?? "PNJ";
  const suffix = Math.floor(Math.random() * 999) + 1;
  
  return `${base} ${suffix}`;
}

/**
 * Trouve ou crée des extras pour remplir une scène.
 */
export async function ensureSceneExtras(
  prisma: PrismaClient,
  input: {
    sceneId: string;
    locationId: string;
    projectId: string;
    requiredExtras: Array<{
      archetype: SceneExtra["archetype"];
      anchorSlot: string;
    }>;
  }
): Promise<SceneExtra[]> {
  // Charger extras existants
  const existing = await loadSceneExtras(prisma, {
    sceneId: input.sceneId,
    locationId: input.locationId,
    projectId: input.projectId,
  });

  const result: SceneExtra[] = [];

  for (const req of input.requiredExtras) {
    // Réutiliser un extra existant du même archetype/slot si possible
    const reused = existing.find(
      (e) => e.archetype === req.archetype && e.anchorSlot === req.anchorSlot
    );

    if (reused) {
      result.push(reused);
    } else {
      // Créer un nouvel extra
      const newExtra: SceneExtra = {
        id: `extra-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
        sceneId: input.sceneId,
        archetype: req.archetype,
        visualSignature: generateVisualSignature(req.archetype),
        anchorSlot: req.anchorSlot,
        reusePriority: 70,
        canSpeak: false,
      };
      
      await persistSceneExtra(prisma, newExtra);
      result.push(newExtra);
    }
  }

  return result;
}

/**
 * Génère une signature visuelle cohérente pour un archetype.
 */
function generateVisualSignature(archetype: SceneExtra["archetype"]): SceneExtra["visualSignature"] {
  const templates: Record<string, SceneExtra["visualSignature"]> = {
    bartender: { genderPresentation: "masculine", outfit: "apron, shirt", silhouette: "stocky" },
    client: { genderPresentation: "varied", outfit: "casual wear", silhouette: "average" },
    guard: { genderPresentation: "masculine", outfit: "armor, uniform", silhouette: "muscular" },
    server: { genderPresentation: "feminine", outfit: "uniform, apron", silhouette: "slender" },
    merchant: { genderPresentation: "masculine", outfit: "robes, vest", silhouette: "rotund" },
    crowd: { genderPresentation: "varied", outfit: "varied", silhouette: "varied" },
  };

  return templates[archetype] ?? { outfit: "generic", silhouette: "average" };
}
